<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/13.0.0">
	<PropertyGroup>
		<Version>0.0.0.0</Version>
		<LangVersion>preview</LangVersion>

		<Author>veyn, croizat</Author>
		<Name>Visland</Name>
		<InternalName>visland</InternalName>
		<Punchline>自動化無人島各項活動</Punchline>
		<Description>自動化採集、開拓工坊排班等無人島相關作業。</Description>
		<RepoUrl>https://github.com/ffxiv-tc-port/visland</RepoUrl>
		<IconUrl>https://raw.githubusercontent.com/ffxiv-tc-port/DalamudPluginsTC/main/icons/visland.png</IconUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))'">
		<DalamudLibPath>$(DALAMUD_HOME)/</DalamudLibPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AutoRetainerAPI\AutoRetainerAPI\AutoRetainerAPI.csproj" />
		<ProjectReference Include="..\ECommons\ECommons\ECommons.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Workshop\Data\workshop-seasons.json" LogicalName="visland.Workshop.Data.workshop-seasons.json" />
		<EmbeddedResource Include="Workshop\Data\mji-craft-map.json" LogicalName="visland.Workshop.Data.mji-craft-map.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="LanguageChineseTraditional.ini" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
